package com.strategy.model;

public enum InterfaceName {
    LOGIN,BUY,SELL,CANCEL,ADDMARGIN,GETLIST,GETHOLDLIST,GETHISTORYLIST,GETENTRUSTDETAILLIST,GETQUOTATION,GETRISEFALL,GETUSERINFO,GETUSERFUND
}
