server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.23.11:3306/strategy
    username: root
    password: root@sg

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*