package com.sangame.hjm.model;

public enum InterfaceName {
    UPDATEVERSION,GETBANNERTURN,GETHOMESUBCATEGORY,KEYWORDSEARCH,SEARCHPROJECTFORCONDITION,SEARCHCATEGORY,
    SEARCHYOURLIKE,STOREDETAILS,ONLINEMESSAGE,SEARCHINVESTMENT,PROJECTCUSTOM,BUSINESSENTER,GETHOMEJOINHEADLINE,SEARCHSUBCATEGORYBYCATEGORYID
}
